### ISSUE TITLE
Crashing on Startup

### ISSUE THREAD

**Issue by nickkeane** [GregTechCEu/GregTech-Modern-Community-Pack#55]
Version: GT Modern Pack 1.9.0
Log: https://mclo.gs/4ZkN0BP

An error seems to occur when creating mod inventoryessentials, during CONSTRUCT stage

Sometimes it will work and go through into the main menu.

**Comment by norwayman22** [comment]
This looks like a duplicate of issue #54 that I opened a few hours earlier

**Comment by nickkeane** [comment]
Is your crash caused by inventorytweaks not being constructed?

**Comment by norwayman22** [comment]
No, but both of our logs show an error saying the variable "fog_distance" is undefined, which could also be the cause. I do however get the exact same error as you when I remove shimmer (thought that would fix it). Because then I get this error with the cause showing any one of Blay's mods (inventorytweaks is one of them).

Either way it's all connected somehow.

**Comment by norwayman22** [comment]
Hey, v1.9.1 of the modpack released a few days ago and fixed the crash caused by Blay's mods for me. Did you try it yet?

**Comment by norwayman22** [comment]
So after updating to 1.9.1, it's still the same story for me. The game crashes on startup, with Shimmer looking like the main cause. And removing that changes the crash to being caused by one of Blay's mods failing to load, cycling through all of them each time. Removing Shimmer + all of Blay's mods is the only way my game does not crash on startup.

**Comment by nickkeane** [comment]
Crashes for me on v1.10, could not construct invetoryessentials

**Comment by norwayman22** [comment]
Yep, im also crashing on 1.10

**Comment by ursamina** [comment]
this vexes me

**Comment by Doon11** [comment]
I ran into this on the latest pack version (1.10.1) but I also found a far less invasive fix. Downgrading Crafting Tweaks back one version (to 18.2.3) fixes it for me on a clean install without touching anything else.

**Comment by nickkeane** [comment]
That seems to work. There's probably something with inventorytweaks and craftingtweaks causing an issue w/ the latest versions.

**Comment by norwayman22** [comment]
That fixes it for me too. Even the other crash I had that seemed to be caused by Shimmer resolves itself too by just downgrading Crafting Tweaks.

**Comment by JustinHuPrime** [comment]
I am also crashing due to "could not reload shaders" which eventually complains about `Invalid shaders/core/particle.json: Couldn't compile vertex program (vanilla, particle) : 0(23) : error C1503: undefined variable "fog_distance"`

I've attached a crash log at [crash-2024-09-08_20.58.16-client.txt](https://github.com/user-attachments/files/16925169/crash-2024-09-08_20.58.16-client.txt)

**Comment by hrtsgs** [comment]
Downgrading Crafting Tweaks still works. But not from the current version 18.2.5 to 18.2.4. Version 18.2.3 works fine.

**Comment by ursamina** [comment]
Can anyone on this thread confirm this happens on latest? I can't reproduce this at all :concern:

**Comment by adrian-aaen** [comment]
I stopped having the issue at some point. Not sure when exactly, but it might have been fixed from 1.13.0 for me.

**Comment by KohKaiSern** [comment]
I think we can safely close this issue now. It's been a year, and it seems to be an issue with a release of CPM that is outdated at this point.
